fun main() {
    println("Hello World!")
    val array = MyArray(10)
    array.addNewElement(1)
    array.addNewElement(2)
    array.addNewElement(3)
    array.addNewElement(4)
    array.printArray()
    array.addNewElement(3, 7)
    array.printArray()
    array.findElement(1)
    array.addNewElement(5)
    array.addNewElement(6)
    array.addNewElement(7)
    array.addNewElement(7, 10)
    array.addNewElement(8, 11)
    array.addNewElement(9, 102)
    array.printArray()
    array.deleteElement(7)
    array.printArray()
    array.deleteElement(1L)
    array.printArray()
    array.deleteElement(2L)
    array.printArray()
    println(array.arraySize())
    array.addNewElement(1)
    array.addNewElement(2)
    array.addNewElement(3)
    array.addNewElement(4)
    array.addNewElement(1)
    array.addNewElement(2)
    array.addNewElement(3)
    array.addNewElement(4)
    array.printArray()
    array.deleteElement(4L)
    array.printArray()
    array.addNewElement(1)
    array.addNewElement(2)
    array.addNewElement(33)
    array.addNewElement(14)
    array.printArray()

}